### ISSUE TITLE
 Undefined variable: who_followed in tm_notifications_chapter_flag_flag() (line 80 of /tm_notifications_chapter/tm_notifications_chapter.module).

### ISSUE THREAD

**Issue by andrysobolev** [travelmassive/massiveplatform#66]
//
/**
 * Implement hook_flag_flag()
 */
function tm_notifications_chapter_flag_flag($flag, $entity_id, $account, $flagging) {
  // We want to target the signup flag on nodes.
  if ($flag->name == 'signup' && $flag->entity_type == 'node') {
    $node = node_load($entity_id);
    // Only for event nodes.
    if ($node->type == 'chapter') {

      // send welcome message to the user
      tm_notifications_notify('user_chapter_join_welcome_member', $account, array('node' => $node));

      // notify each owner of the organizational profile that they have a new follower
      foreach ($node->field_chapter_leaders['und'] as $leader) {
        $leader = user_load($leader['target_id']);

        // set profile url (either friendly url or community url)
        $who_joined = user_load($account->uid);
        $profile_url = "community/" . $who_followed->name;
        if (count($who_joined->field_friendly_url) > 0) { 
          $profile_url = $who_joined->field_friendly_url['und']['0']['value'];
        } 

        tm_notifications_notify('user_chapter_join_notify_leaders', $leader, array('node' => $node, 'user' => $leader, '__PROFILE_URL__' => $profile_url));
      }
    }
  }
}

**Comment by travelmassive** [comment]
Fixed

if ($leader == null) { continue; }
