### ISSUE TITLE
New to this platform and drupal

### ISSUE THREAD

**Issue by akjagetia** [travelmassive/massiveplatform#84]
I might look stupid if I ask this but I am having an issue while installing travel_massive profile with my new drupal installation. I am getting an error like: 
The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as sites/all/modules. Missing modules: Tm_sample_content, Tm_notifications_welcome.

Could you please guide me through this and how to do it ?

Thanks,
Ankit

**Comment by travelmassive** [comment]
Hi Ankit

Are you installing this on top of an existing Drupal install or using our sample database + drupal provided?

Regards
Ian
